//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftEtalonnageMultiPlateforme.Resources.Langue {
    using System;


    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppRessources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppRessources()
        {
        }

        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoftEtalonnageMultiPlateforme.Resources.Langue.AppRessources", typeof(AppRessources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à en-US.
        /// </summary>
        internal static string current_language
        {
            get
            {
                return ResourceManager.GetString("current_language", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose your FontSize :.
        /// </summary>
        internal static string FontSizePickerTitle
        {
            get
            {
                return ResourceManager.GetString("FontSizePickerTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose your language :.
        /// </summary>
        internal static string LanguagePickerTitle
        {
            get
            {
                return ResourceManager.GetString("LanguagePickerTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose your theme :.
        /// </summary>
        internal static string ThemePickerTitle
        {
            get
            {
                return ResourceManager.GetString("ThemePickerTitle", resourceCulture);
            }
        }

        internal static string Login
        {
            get
            {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }

        internal static string EnterLogin
        {
            get
            {
                return ResourceManager.GetString("EnterLogin", resourceCulture);
            }
        }

        internal static string EnterName
        {
            get
            {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }

        internal static string EnterSurname
        {
            get
            {
                return ResourceManager.GetString("EnterSurname", resourceCulture);
            }
        }

        internal static string EnterSignatureName
        {
            get
            {
                return ResourceManager.GetString("EnterSignatureName", resourceCulture);
            }
        }

        internal static string EnterPasswd
        {
            get
            {
                return ResourceManager.GetString("EnterPasswd", resourceCulture);
            }
        }

        internal static string UpdatePasswd
        {
            get
            {
                return ResourceManager.GetString("UpdatePasswd", resourceCulture);
            }
        }

        internal static string Name
        {
            get
            {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        internal static string Surname
        {
            get
            {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }

        internal static string Passwd
        {
            get
            {
                return ResourceManager.GetString("Passwd", resourceCulture);
            }
        }

        internal static string UserNameSignature
        {
            get
            {
                return ResourceManager.GetString("UserNameSignature", resourceCulture);
            }
        }

        internal static string Role
        {
            get
            {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }

        internal static string AddUser
        {
            get
            {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }

        internal static string CreateUser
        {
            get
            {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }

        internal static string UpdateUser
        {
            get
            {
                return ResourceManager.GetString("UpdateUser", resourceCulture);
            }
        }

        internal static string DeleteUser
        {
            get
            {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }

        internal static string Logout
        {
            get
            {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }

        internal static string BackPage
        {
            get
            {
                return ResourceManager.GetString("BackPage", resourceCulture);
            }
        }

        internal static string Cancel
        {
            get
            {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        internal static string UserCatalogue
        {
            get
            {
                return ResourceManager.GetString("UserCatalogue", resourceCulture);
            }
        }

        internal static string PersonalInfo
        {
            get
            {
                return ResourceManager.GetString("PersonalInfo", resourceCulture);
            }
        }

        internal static string LoginPage
        {
            get
            {
                return ResourceManager.GetString("LoginPage", resourceCulture);
            }
        }

        internal static string UpdateUserPage
        {
            get
            {
                return ResourceManager.GetString("UpdateUserPage", resourceCulture);
            }
        }

        internal static string CreateUserPage
        {
            get
            {
                return ResourceManager.GetString("CreateUserPage", resourceCulture);
            }
        }

        internal static string MainPage
        {
            get
            {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        internal static string UploadSignature
        {
            get
            {
                return ResourceManager.GetString("UploadSignature", resourceCulture);
            }
        }
    }
}
